/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'amber.ved' at '3/28/17 10:56 AM' with Gradle 2.14.1
 *
 * @author amber.ved, @date 3/28/17 10:56 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
